<MainWindow>:
    ScreenManager:
        id: srcrn_main
        Screen:
            id: scrn_login
            name: 'scrn_login'
        Screen:
            id: scrn_ventas
            name: 'scrn_ventas'
        Screen:
            id: scrn_inventario
            name: 'scrn_inventario'    
        Screen:
            id: scrn_usuarios
            name: 'scrn_usuarios'
        Screen:
            id: scrn_reportes
            name: 'scrn_reportes'